objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: broker-config
    namespace: openshift-ansible-service-broker
    labels:
      app: openshift-ansible-service-broker
  data:
    broker-config: |
      registry:
        - type: rhcc
          name: rh
          url:  https://registry.redhat.io
          org:
          tag:  v3.11.59
          white_list: [.*-apb$]

          black_list: [.*automation-broker-apb$]

          auth_type: "secret"
          auth_name: "asb-registry-auth"

        - type: local_openshift
          name: localregistry
          namespaces: ['openshift']
          white_list: [.*-apb$]

      dao:
        type: crd
      log:
        stdout: true
        level: info
        color: true
      openshift:
        host: ""
        ca_file: ""
        bearer_token_file: ""
        namespace: openshift-ansible-service-broker
        sandbox_role: edit
        image_pull_policy: Always
        keep_namespace: false
        keep_namespace_on_error: false
      broker:
        dev_broker: false
        bootstrap_on_startup: true
        refresh_interval: 600s
        launch_apb_on_bind: false
        output_request: false
        recovery: true
        ssl_cert_key: /etc/tls/private/tls.key
        ssl_cert: /etc/tls/private/tls.crt
        auto_escalate: False
        auth:
          - type: basic
            enabled: false
      secrets:
        - title: backup-nfs-auth
          apb_name: localregistry-backup-pvc-apb
          secret: ${NFS_BKUP_SECRET}
